name: AlJazeera EPG Update

on:
  schedule:
    - cron: '0 */12 * * *' # تحديث كل 12 ساعة
  workflow_dispatch: # زر للتشغيل اليدوي

permissions:
  contents: write # ضروري جداً للسماح للأكشن برفع الملفات

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install requests beautifulsoup4

      - name: Run Scraper
        run: python scraper.py

      - name: Commit and Push
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add aljazeera_epg.xml
          # المحاولة فقط إذا كان هناك تغيير لعدم إيقاف الأكشن بخطأ
          git commit -m "Update AlJazeera EPG Data" || echo "No changes to commit"
          git push
